package com.missionapp;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.pdf.PdfDocument;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.util.*;
public class MainActivity extends Activity{
 LinearLayout box; JSONObject cur; ArrayList<JSONObject> data=new ArrayList<>();
 final int DAILY=39000000,MULTI=35000000,SUBURB=15000000,HOLIDAY=16000000;
 String[] people={"احسان صنعتی","الهه ناجی","امیرمحمد گلک","امین ترابی نیا","بنفشه رئیسی دهکردی","بهمن لاله زارزاده","ستوده ملکی","سعید سوهانی","سوگند حداد","سهیل قاسم پور مطلق","سیدعلی سعادتمندی","علی  رزاقی","فرزاد میرآبادی دستگردی","گویک کارپیانس","مریم فریدون فاراب","معصومه غلامی","مهدی جوادی مجره","مهدی شاهقلی دستگردی","مهدی فراهانی","مهدی مردانپورجرتوده","نیما فیروزان بلسی"};
 String[] devices={"ADVIA 2120","ADVIA 2120i","ADVIA 360","ADVIA 560","ADVIA Centaur CP","ADVIA Centaur XP","ADVIA Centaur XPT","ADVIA Chemistry 1800","Atellica CH 930 Analyzer","Atellica IM 1300 Analyzer","Atellica IM 1600 Analyzer","Atellica MagLine","Atellica Solution","Atellica UAS 800","BEP2000","BFT II","CLINITEK ADVANTUS","CLINITEK Novus","CLINITEK STATUS","epoc Host","epoc Reader","IMMULITE 2000","IMMULITE 2000 XPi","PCR QS 5","PFA-200","Prisca","RAPIDCHEM 744","RAPIDCHEM 754","RAPIDPoint 500","RL348EX","VersaCell X3"};
 String[] payers={"شخص","شرکت"}; String[] cats={"هزینه شهر تهران","هزینه تردد بین شهری","هزینه تردد درون شهری","سایر هزینه ها"}; String[] tehranItems={"بازار (خرید لوازم و ابزار کار)","ترمینال یا فرودگاه به منزل","سایت مشتری به سایت مشتری","سایت مشتری به شرکت","سایت مشتری به منزل","شرکت به ترمینال یا فرودگاه","شرکت به سایت مشتری","شرکت به منزل","فرودگاه یا ترمینال به شرکت","منزل به ترمینال یا فرودگاه","منزل به سایت مشتری","منزل به شرکت"};
 public void onCreate(Bundle b){super.onCreate(b);load();home();}
 TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setPadding(12,10,12,10);return v;}
 EditText ed(String h){EditText v=new EditText(this);v.setHint(h);v.setTextSize(16);v.setGravity(Gravity.RIGHT);return v;}
 Button bt(String s){Button v=new Button(this);v.setText(s);return v;}
 Spinner spinner(String[] a){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a));return s;}
 void base(String title){box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(12,12,12,12);box.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);setContentView(box);box.addView(tv(title,23));}
 void add(String l,View v){box.addView(tv(l,14));box.addView(v);}
 String money(double x){return String.format(Locale.US,"%,.0f",x);} String words(long n){String[] u={"صفر","یک","دو","سه","چهار","پنج","شش","هفت","هشت","نه","ده","یازده","دوازده","سیزده","چهارده","پانزده","شانزده","هفده","هجده","نوزده","بیست","بیست و یک","بیست و دو","بیست و سه","بیست و چهار","بیست و پنج","بیست و شش","بیست و هفت","بیست و هشت","بیست و نه"};String[] t={"","","بیست","سی","چهل","پنجاه","شصت","هفتاد","هشتاد","نود"};String[] h={"","","صد","دویست","سیصد","چهارصد","پانصد","ششصد","هفتصد","هشتصد","نهصد"};if(n<30)return u[(int)n];if(n<100)return t[(int)n/10]+(n%10>0?" و "+u[(int)n%10]:"");if(n<1000)return h[(int)n/100]+(n%100>0?" و "+words(n%100):"");if(n<1000000)return words(n/1000)+" هزار"+(n%1000>0?" و "+words(n%1000):"");if(n<1000000000)return words(n/1000000)+" میلیون"+(n%1000000>0?" و "+words(n%1000000):"");return words(n/1000000000)+" میلیارد"+(n%1000000000>0?" و "+words(n%1000000000):"");} String amountWords(double v){return words(Math.round(v))+" ریال";} 
 double num(EditText e){try{return Double.parseDouble(e.getText().toString().replace(",",""));}catch(Exception x){return 0;}}
 double expenseSum(JSONObject m,String cat){double s=0;JSONArray a=m.optJSONArray("expenses");if(a!=null)for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(cat==null||cat.equals(o.optString("category")))s+=o.optDouble("amount");}return s;}
 double missionPay(JSONObject m){double d=m.optDouble("days",1),h=m.optDouble("holiday",0);if(m.optBoolean("suburb"))return d*SUBURB+h*HOLIDAY;return (d==1?DAILY:d*MULTI)+h*HOLIDAY;} double reimbursable(JSONObject m,String payerKey,String amountKey){return "شخص".equals(payer(m,payerKey))?m.optDouble(amountKey):0;} double total(JSONObject m){return missionPay(m)+reimbursable(m,"hotelPayer","hotel")+reimbursable(m,"goPayer","ticketGo")+reimbursable(m,"backPayer","ticketBack")+reimbursable(m,"cancelGoPayer","cancelGo")+reimbursable(m,"cancelBackPayer","cancelBack")+expenseSum(m,null);} String payer(JSONObject m,String key){return m.optString(key,"شخص");} int[] gregorianToJalali(int gy,int gm,int gd){int[] gdm={0,31,28,31,30,31,30,31,31,30,31,30,31};int gy2=gy-1600,gm2=gm-1,gd2=gd-1;int gdn=365*gy2+(gy2+3)/4-(gy2+99)/100+(gy2+399)/400;for(int i=0;i<gm2;i++)gdn+=gdm[i];if(gm2>1&&((gy%4==0&&gy%100!=0)||gy%400==0))gdn++;gdn+=gd2;int jdn=gdn-79;int j_np=jdn/12053;jdn%=12053;int jy=979+33*j_np+4*(jdn/1461);jdn%=1461;if(jdn>=366){jy+=(jdn-1)/365;jdn=(jdn-1)%365;}int jm=jdn<186?1+jdn/31:7+(jdn-186)/30;int jd=1+(jdn% (jdn<186?31:30));return new int[]{jy,jm,jd};}
int days360(int sy,int sm,int sd,int ey,int em,int ed){if(sd==31)sd=30;if(ed==31&&(sd==30||sd==31))ed=30;return 360*(ey-sy)+30*(em-sm)+(ed-sd);}
void validate7(String end){if(end==null||end.trim().isEmpty())return;try{String[] p=end.trim().replace("-","/").split("/");if(p.length!=3)return;int y=Integer.parseInt(p[0]),mo=Integer.parseInt(p[1]),da=Integer.parseInt(p[2]);int[] now=gregorianToJalali(Calendar.getInstance().get(Calendar.YEAR),Calendar.getInstance().get(Calendar.MONTH)+1,Calendar.getInstance().get(Calendar.DAY_OF_MONTH));int d;if(y>=1200&&y<1700)d=days360(y,mo,da,now[0],now[1],now[2]);else{Calendar e=Calendar.getInstance();e.setLenient(false);e.set(y,mo-1,da,0,0,0);e.getTime();Calendar n=Calendar.getInstance();n.set(Calendar.HOUR_OF_DAY,0);n.set(Calendar.MINUTE,0);n.set(Calendar.SECOND,0);n.set(Calendar.MILLISECOND,0);d=(int)((n.getTimeInMillis()-e.getTimeInMillis())/86400000L);}if(d>7)throw new IllegalArgumentException("بیشتر از 7 روز از مأموریت گذشته و هزینه‌ها طبق Excel قابل پرداخت نیست");}catch(NumberFormatException x){}catch(IllegalArgumentException x){if(x.getMessage()!=null&&x.getMessage().contains("بیشتر از 7 روز"))throw x;}}
 void home(){base("مدیریت هزینه مأموریت");Button n=bt("＋ مأموریت جدید");n.setOnClickListener(v->{cur=new JSONObject();try{cur.put("expenses",new JSONArray());}catch(Exception e){}edit();});box.addView(n);ScrollView sc=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);for(JSONObject m:data){Button x=bt(m.optString("subject","بدون موضوع")+" | "+m.optString("destination","")+" | "+money(total(m))+" ریال");x.setOnClickListener(v->{cur=m;edit();});list.addView(x);}sc.addView(list);box.addView(sc,new LinearLayout.LayoutParams(-1,0,1));}
 int index(String[] a,String s){for(int i=0;i<a.length;i++)if(a[i].equals(s))return i;return 0;}
 void edit(){base(cur.length()==0?"مأموریت جدید":"ویرایش مأموریت");
  EditText form=ed("شماره فرم ماموریت"),service=ed("شماره سرویس"),subject=ed("موضوع"),dest=ed("مقصد"),start=ed("تاریخ شروع"),end=ed("تاریخ پایان"),startTime=ed("زمان شروع"),endTime=ed("زمان پایان"),days=ed("تعداد روز مأموریت"),holiday=ed("تعداد روز تعطیل"),hotel=ed("هزینه هتل"),go=ed("هزینه بلیط رفت"),back=ed("هزینه بلیط برگشت"),cancelGo=ed("هزینه کنسلی بلیط رفت"),cancelBack=ed("هزینه کنسلی بلیط برگشت"),goNo=ed("شماره بلیط رفت"),backNo=ed("شماره بلیط برگشت");
  form.setText(cur.optString("form"));service.setText(cur.optString("service"));subject.setText(cur.optString("subject"));dest.setText(cur.optString("destination"));start.setText(cur.optString("start"));end.setText(cur.optString("end"));startTime.setText(cur.optString("startTime"));endTime.setText(cur.optString("endTime"));days.setText(String.valueOf(cur.optDouble("days",1)));holiday.setText(String.valueOf(cur.optDouble("holiday",0)));hotel.setText(String.valueOf(cur.optDouble("hotel",0)));go.setText(String.valueOf(cur.optDouble("ticketGo",0)));back.setText(String.valueOf(cur.optDouble("ticketBack",0)));cancelGo.setText(String.valueOf(cur.optDouble("cancelGo",0)));cancelBack.setText(String.valueOf(cur.optDouble("cancelBack",0)));goNo.setText(cur.optString("goNo"));backNo.setText(cur.optString("backNo"));
  Spinner ps=spinner(people),ds=spinner(devices),hp=spinner(payers),gp=spinner(payers),bp=spinner(payers),cgp=spinner(payers),cbp=spinner(payers);ps.setSelection(index(people,cur.optString("person")));ds.setSelection(index(devices,cur.optString("device")));hp.setSelection(index(payers,payer(cur,"hotelPayer")));gp.setSelection(index(payers,payer(cur,"goPayer")));bp.setSelection(index(payers,payer(cur,"backPayer")));cgp.setSelection(index(payers,payer(cur,"cancelGoPayer")));cbp.setSelection(index(payers,payer(cur,"cancelBackPayer")));
  add("شماره فرم",form);add("شماره سرویس",service);add("نام کارشناس",ps);add("دستگاه",ds);add("موضوع",subject);add("مقصد",dest);add("تاریخ شروع",start);add("تاریخ پایان",end);add("زمان شروع",startTime);add("زمان پایان",endTime);add("روز مأموریت",days);add("روز تعطیل",holiday);
  CheckBox suburb=new CheckBox(this);suburb.setText("حومه تهران");suburb.setChecked(cur.optBoolean("suburb",false));box.addView(suburb);
  add("هتل",hotel);add("پرداخت هتل توسط",hp);add("بلیط رفت",go);add("پرداخت بلیط رفت توسط",gp);add("شماره بلیط رفت",goNo);add("بلیط برگشت",back);add("پرداخت بلیط برگشت توسط",bp);add("شماره بلیط برگشت",backNo);add("کنسلی بلیط رفت",cancelGo);add("پرداخت کنسلی رفت توسط",cgp);add("کنسلی بلیط برگشت",cancelBack);add("پرداخت کنسلی برگشت توسط",cbp);
  TextView sum=tv("جمع کل: "+money(total(cur))+" ریال",19);box.addView(sum);
  LinearLayout exList=new LinearLayout(this);exList.setOrientation(LinearLayout.VERTICAL);box.addView(tv("ریز هزینه‌ها",18));box.addView(exList);render(exList,sum);
  Button ex=bt("＋ افزودن ردیف هزینه");ex.setOnClickListener(v->expenseDialog(exList,sum));box.addView(ex);
  Button save=bt("ذخیره مأموریت");save.setOnClickListener(v->{try{validate7(end.getText().toString());cur.put("form",form.getText().toString());cur.put("service",service.getText().toString());cur.put("person",ps.getSelectedItem().toString());cur.put("device",ds.getSelectedItem().toString());cur.put("subject",subject.getText().toString());cur.put("destination",dest.getText().toString());cur.put("start",start.getText().toString());cur.put("end",end.getText().toString());cur.put("startTime",startTime.getText().toString());cur.put("endTime",endTime.getText().toString());cur.put("days",num(days));cur.put("holiday",num(holiday));cur.put("suburb",suburb.isChecked());cur.put("hotel",num(hotel));cur.put("ticketGo",num(go));cur.put("ticketBack",num(back));cur.put("cancelGo",num(cancelGo));cur.put("cancelBack",num(cancelBack));cur.put("goNo",goNo.getText().toString());cur.put("backNo",backNo.getText().toString());cur.put("hotelPayer",hp.getSelectedItem().toString());cur.put("goPayer",gp.getSelectedItem().toString());cur.put("backPayer",bp.getSelectedItem().toString());cur.put("cancelGoPayer",cgp.getSelectedItem().toString());cur.put("cancelBackPayer",cbp.getSelectedItem().toString());if(!data.contains(cur))data.add(cur);save();home();}catch(Exception e){toast(e.getMessage());}});box.addView(save);
  Button pdf=bt("ساخت گزارش PDF");pdf.setOnClickListener(v->pdf(cur));box.addView(pdf);Button reset=bt("بازگشت");reset.setOnClickListener(v->home());box.addView(reset);
 }
 void expenseDialog(LinearLayout list,TextView sum){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);Spinner cat=spinner(cats);Spinner ti=spinner(tehranItems);cat.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){ti.setVisibility(pos==0?View.VISIBLE:View.GONE);}public void onNothingSelected(android.widget.AdapterView<?> p){}});EditText date=ed("تاریخ"),desc=ed("شرح"),invoice=ed("شماره فاکتور"),amount=ed("مبلغ");l.addView(cat);l.addView(ti);l.addView(date);l.addView(desc);l.addView(invoice);l.addView(amount);new AlertDialog.Builder(this).setTitle("افزودن هزینه").setView(l).setNegativeButton("انصراف",null).setPositiveButton("ثبت",(d,w)->{try{JSONArray a=cur.getJSONArray("expenses");JSONObject o=new JSONObject();o.put("category",cat.getSelectedItem().toString());o.put("tehranItem",ti.getSelectedItem().toString());o.put("date",date.getText().toString());o.put("desc",desc.getText().toString());o.put("invoice",invoice.getText().toString());o.put("amount",num(amount));a.put(o);render(list,sum);}catch(Exception e){toast(e.getMessage());}}).show();}
 void render(LinearLayout list,TextView sum){list.removeAllViews();JSONArray a=cur.optJSONArray("expenses");if(a!=null)for(int i=0;i<a.length();i++){final int k=i;JSONObject o=a.optJSONObject(i);Button x=bt(o.optString("category")+" | "+o.optString("desc")+" | "+money(o.optDouble("amount"))+" ریال  ✕");x.setOnClickListener(v->{a.remove(k);render(list,sum);});list.addView(x);}sum.setText("جمع کل: "+money(total(cur))+" ریال");}
 void save(){try{JSONArray a=new JSONArray();for(JSONObject m:data)a.put(m);getPreferences(0).edit().putString("data",a.toString()).apply();}catch(Exception e){}}
 void load(){try{JSONArray a=new JSONArray(getPreferences(0).getString("data","[]"));for(int i=0;i<a.length();i++)data.add(a.getJSONObject(i));}catch(Exception e){}}
 void toast(String s){Toast.makeText(this,"خطا: "+s,Toast.LENGTH_LONG).show();}
 void pdf(JSONObject m){try{
  PdfDocument d=new PdfDocument();
  Paint q=new Paint(Paint.ANTI_ALIAS_FLAG); q.setTextSize(11); q.setColor(Color.BLACK);
  Paint title=new Paint(Paint.ANTI_ALIAS_FLAG); title.setTextSize(18); title.setTypeface(Typeface.DEFAULT_BOLD); title.setColor(Color.BLACK);
  Paint head=new Paint(Paint.ANTI_ALIAS_FLAG); head.setTextSize(12); head.setTypeface(Typeface.DEFAULT_BOLD); head.setColor(Color.BLACK);
  int W=595,H=842,margin=28;
  ArrayList<String[]> rows=new ArrayList<>();
  rows.add(new String[]{"شماره فرم",m.optString("form"),"شماره سرویس",m.optString("service")});
  rows.add(new String[]{"نام کارشناس",m.optString("person"),"دستگاه",m.optString("device")});
  rows.add(new String[]{"موضوع",m.optString("subject"),"مقصد",m.optString("destination")});
  rows.add(new String[]{"تاریخ شروع",m.optString("start"),"تاریخ پایان",m.optString("end")});
  rows.add(new String[]{"زمان شروع",m.optString("startTime"),"زمان پایان",m.optString("endTime")});
  rows.add(new String[]{"روز مأموریت",String.valueOf(m.optDouble("days",1)),"روز تعطیل",String.valueOf(m.optDouble("holiday",0))});
  rows.add(new String[]{"حومه تهران",m.optBoolean("suburb")?"بله":"خیر","حق مأموریت",money(missionPay(m))+" ریال"});
  PdfDocument.Page p=d.startPage(new PdfDocument.PageInfo.Builder(W,H,1).create()); Canvas c=p.getCanvas();
  c.drawText("گزارش هزینه مأموریت",W/2-90,32,title); int y=48;
  for(String[] r:rows){int h=38; int[] xs={margin,165,295,425,W-margin}; q.setStyle(Paint.Style.STROKE);c.drawRect(xs[0],y,xs[4],y+h,q);for(int i=1;i<4;i++)c.drawLine(xs[i],y,xs[i],y+h,q);q.setStyle(Paint.Style.FILL);for(int i=0;i<4;i++){drawRtl(c,r[i],xs[i],y+9,xs[i+1]-xs[i],20,(i%2==0)?head:q);}y+=h;}
  y+=14; c.drawText("ریز هزینه‌ها",W/2-55,y,title); y+=12;
  String[] th={"دسته","شرح","تاریخ","فاکتور","مبلغ"};
  int[] tx={margin,145,300,395,465,W-margin}; q.setStyle(Paint.Style.STROKE);c.drawRect(margin,y, W-margin,y+32,q);for(int i=1;i<tx.length-1;i++)c.drawLine(tx[i],y,tx[i],y+32,q);q.setStyle(Paint.Style.FILL);
  for(int i=0;i<th.length;i++)drawRtl(c,th[i],tx[i],y+7,tx[i+1]-tx[i],18,head); y+=32;
  JSONArray ar=m.optJSONArray("expenses"); double[] sums={0,0,0,0}; String[] cn={"هزینه شهر تهران","هزینه تردد بین شهری","هزینه تردد درون شهری","سایر هزینه ها"};
  if(ar!=null)for(int i=0;i<ar.length()&&y<730;i++){JSONObject o=ar.optJSONObject(i);String cat=o.optString("category");String[] rr={cat,o.optString("desc"),o.optString("date"),o.optString("invoice"),money(o.optDouble("amount"))};q.setStyle(Paint.Style.STROKE);c.drawRect(margin,y,W-margin,y+28,q);for(int z=1;z<tx.length-1;z++)c.drawLine(tx[z],y,tx[z],y+28,q);q.setStyle(Paint.Style.FILL);for(int z=0;z<5;z++)drawRtl(c,rr[z],tx[z],y+6,tx[z+1]-tx[z],18,q);for(int z=0;z<cn.length;z++)if(cn[z].equals(cat))sums[z]+=o.optDouble("amount");y+=28;}
  y+=10;for(int i=0;i<4;i++){drawRtl(c,cn[i]+": "+money(sums[i])+" ریال",W-260,y,230,20,q);y+=20;}drawRtl(c,"جمع کل قابل پرداخت: "+money(total(m))+" ریال",W-320,y,290,24,head);
  d.finishPage(p);

  p=d.startPage(new PdfDocument.PageInfo.Builder(W,H,2).create()); c=p.getCanvas();c.drawText("روکش سند حسابداری",W/2-78,34,title);y=54;
  String[][] cover={{"واحد / دستگاه",m.optString("device")},{"نام کارشناس",m.optString("person")},{"مقصد",m.optString("destination")},{"موضوع مأموریت",m.optString("subject")},{"شماره فرم",m.optString("form")},{"شماره سرویس",m.optString("service")},{"بازه مأموریت",m.optString("start")+" تا "+m.optString("end")},{"مبلغ سند",money(total(m))+" ریال"},{"مبلغ به حروف",amountWords(total(m))}};
  for(String[] r:cover){int h=r[0].equals("مبلغ به حروف")?52:42;q.setStyle(Paint.Style.STROKE);c.drawRect(margin,y,W-margin,y+h,q);c.drawLine(205,y,205,y+h,q);q.setStyle(Paint.Style.FILL);drawRtl(c,r[0],margin,y+10,175,20,head);drawRtl(c,r[1],215,y+10,W-margin-215,h-12,q);y+=h;}
  y+=16;drawRtl(c,"وضعیت پرداخت هزینه‌های مستقیم",W-300,y,270,22,head);y+=10;
  String payLine="هتل: "+payer(m,"hotelPayer")+"   |   بلیط رفت: "+payer(m,"goPayer")+"   |   بلیط برگشت: "+payer(m,"backPayer");
  drawRtl(c,payLine,W-540,y,510,22,q);y+=24;
  drawRtl(c,"کنسلی رفت: "+payer(m,"cancelGoPayer")+"   |   کنسلی برگشت: "+payer(m,"cancelBackPayer"),W-540,y,510,22,q);y+=38;
  drawRtl(c,"تأییدها",W-90,y,80,22,head);y+=12;
  String[] sig={"درخواست کننده","مدیر / مسئول","حسابداری","تأیید نهایی"};for(String x:sig){q.setStyle(Paint.Style.STROKE);c.drawRect(margin,y,W-margin,y+55,q);q.setStyle(Paint.Style.FILL);drawRtl(c,x,margin+12,y+12,180,20,head);drawRtl(c,"نام و امضا: ______________________________",210,y+12,340,20,q);y+=58;}
  d.finishPage(p);
  String fn="Mission_"+System.currentTimeMillis()+".pdf";
  if(Build.VERSION.SDK_INT>=29){ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,fn);v.put(MediaStore.Downloads.MIME_TYPE,"application/pdf");v.put(MediaStore.Downloads.IS_PENDING,1);Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);OutputStream o=getContentResolver().openOutputStream(u);d.writeTo(o);o.close();v.clear();v.put(MediaStore.Downloads.IS_PENDING,0);getContentResolver().update(u,v,null,null);d.close();share(u);}else{File f=new File(getExternalFilesDir(null),fn);OutputStream o=new FileOutputStream(f);d.writeTo(o);o.close();d.close();share(Uri.fromFile(f));}
 }catch(Exception e){toast(e.getMessage());}}
 void drawRtl(Canvas c,String s,float x,float y,float w,float h,Paint p){if(s==null)s="";android.text.TextPaint tp=new android.text.TextPaint(p);tp.setTextAlign(Paint.Align.RIGHT);android.text.StaticLayout sl=new android.text.StaticLayout(s,tp,Math.max(20,(int)w),android.text.Layout.Alignment.ALIGN_OPPOSITE,1f,0f,false);c.save();c.translate(x+w,y);sl.draw(c);c.restore();}
 void share(Uri u){Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/pdf");i.putExtra(Intent.EXTRA_STREAM,u);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"ارسال PDF"));}
}