package com.missionapp;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.pdf.PdfDocument;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity{
 LinearLayout box; EditText person,subject,dest,start,end,days,holiday,hotel,ticketGo,ticketBack; ArrayList<JSONObject> data=new ArrayList<>(); JSONObject cur;
 int daily=39000000,multi=35000000,suburb=15000000,holidayRate=16000000;
 String[] people={"احسان صنعتی","الهه ناجی","امیرمحمد گلک","امین ترابی نیا","بنفشه رئیسی دهکردی","بهمن لاله زارزاده","ستوده ملکی","سعید سوهانی","سوگند حداد","سهیل قاسم پور مطلق","سیدعلی سعادتمندی","علی رزاق","فرزاد میرآبادی دستگردی","گویک کارپیانس","مریم فریدون فاراب","معصومه غلامی","مهدی جوادی مجره","مهدی شاهقلی دستگردی","مهدی فراهانی","مهدی مردانپورجرتوده","نیما فیروزان بلسی"};
 String[] devices={"ADVIA 2120","ADVIA 2120i","ADVIA 360","ADVIA 560","ADVIA Centaur CP","ADVIA Centaur XP","ADVIA Centaur XPT","ADVIA Chemistry 1800","Atellica CH 930 Analyzer","Atellica IM 1300 Analyzer","Atellica IM 1600 Analyzer","Atellica MagLine","Atellica Solution","Atellica UAS 800","BEP2000","BFT II","CLINITEK ADVANTUS","CLINITEK Novus","CLINITEK STATUS","epoc Host","epoc Reader","IMMULITE 2000","IMMULITE 2000 XPi","PCR QS 5","PFA-200","Prisca","RAPIDCHEM 744"};
 public void onCreate(Bundle b){super.onCreate(b);load();home();}
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setPadding(12,12,12,12);return v;}
 EditText e(String h){EditText v=new EditText(this);v.setHint(h);v.setTextSize(16);v.setGravity(Gravity.RIGHT);return v;}
 Button b(String s){Button v=new Button(this);v.setText(s);return v;}
 void base(String s){box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(14,14,14,14);box.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);setContentView(box);box.addView(t(s,23));}
 void home(){base("مدیریت هزینه مأموریت");Button n=b("＋ مأموریت جدید");n.setOnClickListener(v->{cur=new JSONObject();try{cur.put("expenses",new JSONArray());}catch(Exception x){}edit();});box.addView(n);ScrollView sc=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);for(JSONObject m:data){Button x=b(m.optString("subject","بدون موضوع")+" | "+m.optString("destination","")+" | "+money(total(m))+" ریال");x.setOnClickListener(v->{cur=m;edit();});list.addView(x);}sc.addView(list);box.addView(sc,new LinearLayout.LayoutParams(-1,0,1));}
 void add(String label,View v){box.addView(t(label,14));box.addView(v);}
 Spinner sp(String[] a){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a));return s;}
 void edit(){base(cur.length()==0?"مأموریت جدید":"ویرایش مأموریت");
  person=e("نام کارشناس");subject=e("موضوع");dest=e("مقصد");start=e("تاریخ شروع");end=e("تاریخ پایان");days=e("تعداد روز مأموریت");holiday=e("تعداد روز تعطیل");hotel=e("هتل");ticketGo=e("بلیط رفت");ticketBack=e("بلیط برگشت");
  person.setText(cur.optString("person"));subject.setText(cur.optString("subject"));dest.setText(cur.optString("destination"));start.setText(cur.optString("start"));end.setText(cur.optString("end"));days.setText(String.valueOf(cur.optDouble("days",1)));holiday.setText(String.valueOf(cur.optDouble("holiday",0)));hotel.setText(String.valueOf(cur.optDouble("hotel",0)));ticketGo.setText(String.valueOf(cur.optDouble("ticketGo",0)));ticketBack.setText(String.valueOf(cur.optDouble("ticketBack",0)));
  Spinner device=sp(devices);add("کارشناس",person);add("دستگاه",device);add("موضوع",subject);add("مقصد",dest);add("تاریخ شروع",start);add("تاریخ پایان",end);add("روز مأموریت",days);add("روز تعطیل",holiday);add("هتل",hotel);add("بلیط رفت",ticketGo);add("بلیط برگشت",ticketBack);
  CheckBox sub=new CheckBox(this);sub.setText("حومه تهران");sub.setChecked(cur.optBoolean("suburb"));box.addView(sub);
  TextView total=t("جمع کل: "+money(total(cur))+" ریال",19);box.addView(total);
  Button ex=b("＋ افزودن هزینه");box.addView(ex);LinearLayout expenses=new LinearLayout(this);expenses.setOrientation(LinearLayout.VERTICAL);box.addView(expenses);render(expenses,total);
  ex.setOnClickListener(v->dialog(expenses,total));
  Button save=b("ذخیره");save.setOnClickListener(v->{try{cur.put("person",person.getText());cur.put("subject",subject.getText());cur.put("destination",dest.getText());cur.put("start",start.getText());cur.put("end",end.getText());cur.put("days",num(days));cur.put("holiday",num(holiday));cur.put("hotel",num(hotel));cur.put("ticketGo",num(ticketGo));cur.put("ticketBack",num(ticketBack));cur.put("suburb",sub.isChecked());if(!data.contains(cur))data.add(cur);save();home();}catch(Exception x){}});box.addView(save);Button pdf=b("ساخت PDF گزارش و روکش سند");pdf.setOnClickListener(v->pdf(cur));box.addView(pdf);Button back=b("بازگشت");back.setOnClickListener(v->home());box.addView(back);}
 double num(EditText e){try{return Double.parseDouble(e.getText().toString().replace(",",""));}catch(Exception x){return 0;}}
 double total(JSONObject m){double x=m.optDouble("hotel")+m.optDouble("ticketGo")+m.optDouble("ticketBack");JSONArray a=m.optJSONArray("expenses");if(a!=null)for(int i=0;i<a.length();i++)x+=a.optJSONObject(i).optDouble("amount");double d=m.optDouble("days",1);x+=(m.optBoolean("suburb")?d*suburb:(d<=1?daily:d*multi))+m.optDouble("holiday")*holidayRate;return x;}
 String money(double x){return String.format(Locale.US,"%,.0f",x);}
 void dialog(LinearLayout list,TextView sum){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText cat=e("نوع هزینه");EditText desc=e("شرح");EditText amount=e("مبلغ");l.addView(cat);l.addView(desc);l.addView(amount);new AlertDialog.Builder(this).setTitle("افزودن هزینه").setView(l).setNegativeButton("انصراف",null).setPositiveButton("ثبت",(d,w)->{try{JSONArray a=cur.getJSONArray("expenses");JSONObject o=new JSONObject();o.put("category",cat.getText());o.put("desc",desc.getText());o.put("amount",num(amount));a.put(o);render(list,sum);}catch(Exception x){}}).show();}
 void render(LinearLayout list,TextView sum){list.removeAllViews();JSONArray a=cur.optJSONArray("expenses");if(a==null)return;for(int i=0;i<a.length();i++){final int k=i;JSONObject o=a.optJSONObject(i);Button x=b(o.optString("category")+" - "+o.optString("desc")+" - "+money(o.optDouble("amount"))+" ریال ✕");x.setOnClickListener(v->{a.remove(k);render(list,sum);});list.addView(x);}sum.setText("جمع کل: "+money(total(cur))+" ریال");}
 void save(){try{JSONArray a=new JSONArray();for(JSONObject m:data)a.put(m);getPreferences(0).edit().putString("data",a.toString()).apply();}catch(Exception x){}}
 void load(){try{JSONArray a=new JSONArray(getPreferences(0).getString("data","[]"));for(int i=0;i<a.length();i++)data.add(a.getJSONObject(i));}catch(Exception x){}}
 void pdf(JSONObject m){try{PdfDocument d=new PdfDocument();PdfDocument.Page p=d.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());Canvas c=p.getCanvas();Paint q=new Paint();q.setTextSize(16);int y=45;String[] ls={"گزارش هزینه مأموریت","کارشناس: "+m.optString("person"),"دستگاه: "+m.optString("device"),"موضوع: "+m.optString("subject"),"مقصد: "+m.optString("destination"),"شروع: "+m.optString("start"),"پایان: "+m.optString("end"),"هتل: "+money(m.optDouble("hotel")),"بلیط رفت: "+money(m.optDouble("ticketGo")),"بلیط برگشت: "+money(m.optDouble("ticketBack"))};for(String s:ls){c.drawText(s,40,y,q);y+=28;}y+=10;c.drawText("ریز هزینه‌ها:",40,y,q);y+=25;JSONArray a=m.optJSONArray("expenses");if(a!=null)for(int i=0;i<a.length()&&y<770;i++){JSONObject o=a.optJSONObject(i);c.drawText(o.optString("category")+" | "+o.optString("desc")+" | "+money(o.optDouble("amount")),40,y,q);y+=22;}y+=25;c.drawText("جمع کل: "+money(total(m))+" ریال",40,y,q);d.finishPage(p);String fn="Mission_"+System.currentTimeMillis()+".pdf";if(Build.VERSION.SDK_INT>=29){ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,fn);v.put(MediaStore.Downloads.MIME_TYPE,"application/pdf");v.put(MediaStore.Downloads.IS_PENDING,1);Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);OutputStream o=getContentResolver().openOutputStream(u);d.writeTo(o);o.close();v.clear();v.put(MediaStore.Downloads.IS_PENDING,0);getContentResolver().update(u,v,null,null);d.close();share(u);}else{File f=new File(getExternalFilesDir(null),fn);OutputStream o=new FileOutputStream(f);d.writeTo(o);o.close();d.close();share(Uri.fromFile(f));}}catch(Exception x){Toast.makeText(this,"خطا: "+x.getMessage(),Toast.LENGTH_LONG).show();}}
 void share(Uri u){Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/pdf");i.putExtra(Intent.EXTRA_STREAM,u);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"ارسال PDF"));}
}