package com.missionapp;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.pdf.PdfDocument;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.util.*;
public class MainActivity extends Activity{
 LinearLayout box; JSONObject cur; ArrayList<JSONObject> data=new ArrayList<>();
 final int DAILY=39000000,MULTI=35000000,SUBURB=15000000,HOLIDAY=16000000;
 String[] people={"احسان صنعتی","الهه ناجی","امیرمحمد گلک","امین ترابی نیا","بنفشه رئیسی دهکردی","بهمن لاله زارزاده","ستوده ملکی","سعید سوهانی","سوگند حداد","سهیل قاسم پور مطلق","سیدعلی سعادتمندی","علی  رزاقی","فرزاد میرآبادی دستگردی","گویک کارپیانس","مریم فریدون فاراب","معصومه غلامی","مهدی جوادی مجره","مهدی شاهقلی دستگردی","مهدی فراهانی","مهدی مردانپورجرتوده","نیما فیروزان بلسی"};
 String[] devices={"ADVIA 2120","ADVIA 2120i","ADVIA 360","ADVIA 560","ADVIA Centaur CP","ADVIA Centaur XP","ADVIA Centaur XPT","ADVIA Chemistry 1800","Atellica CH 930 Analyzer","Atellica IM 1300 Analyzer","Atellica IM 1600 Analyzer","Atellica MagLine","Atellica Solution","Atellica UAS 800","BEP2000","BFT II","CLINITEK ADVANTUS","CLINITEK Novus","CLINITEK STATUS","epoc Host","epoc Reader","IMMULITE 2000","IMMULITE 2000 XPi","PCR QS 5","PFA-200","Prisca","RAPIDCHEM 744","RAPIDCHEM 754","RAPIDPoint 500","RL348EX","VersaCell X3"};
 String[] payers={"شخص","شرکت"}; String[] cats={"هزینه شهر تهران","هزینه تردد بین شهری","هزینه تردد درون شهری","سایر هزینه ها"}; String[] tehranItems={"بازار (خرید لوازم و ابزار کار)","ترمینال یا فرودگاه به منزل","سایت مشتری به سایت مشتری","سایت مشتری به شرکت","سایت مشتری به منزل","شرکت به ترمینال یا فرودگاه","شرکت به سایت مشتری","شرکت به منزل","فرودگاه یا ترمینال به شرکت","منزل به ترمینال یا فرودگاه","منزل به سایت مشتری","منزل به شرکت"};
 public void onCreate(Bundle b){super.onCreate(b);load();home();}
 TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setPadding(12,10,12,10);return v;}
 EditText ed(String h){EditText v=new EditText(this);v.setHint(h);v.setTextSize(16);v.setGravity(Gravity.RIGHT);return v;}
 Button bt(String s){Button v=new Button(this);v.setText(s);return v;}
 Spinner spinner(String[] a){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a));return s;}
 void base(String title){box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(12,12,12,12);box.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);setContentView(box);box.addView(tv(title,23));}
 void add(String l,View v){box.addView(tv(l,14));box.addView(v);}
 String money(double x){return String.format(Locale.US,"%,.0f",x);} String words(long n){String[] u={"صفر","یک","دو","سه","چهار","پنج","شش","هفت","هشت","نه","ده","یازده","دوازده","سیزده","چهارده","پانزده","شانزده","هفده","هجده","نوزده","بیست","بیست و یک","بیست و دو","بیست و سه","بیست و چهار","بیست و پنج","بیست و شش","بیست و هفت","بیست و هشت","بیست و نه"};String[] t={"","","بیست","سی","چهل","پنجاه","شصت","هفتاد","هشتاد","نود"};String[] h={"","","صد","دویست","سیصد","چهارصد","پانصد","ششصد","هفتصد","هشتصد","نهصد"};if(n<30)return u[(int)n];if(n<100)return t[(int)n/10]+(n%10>0?" و "+u[(int)n%10]:"");if(n<1000)return h[(int)n/100]+(n%100>0?" و "+words(n%100):"");if(n<1000000)return words(n/1000)+" هزار"+(n%1000>0?" و "+words(n%1000):"");if(n<1000000000)return words(n/1000000)+" میلیون"+(n%1000000>0?" و "+words(n%1000000):"");return words(n/1000000000)+" میلیارد"+(n%1000000000>0?" و "+words(n%1000000000):"");} String amountWords(double v){return words(Math.round(v))+" ریال";} 
 double num(EditText e){try{return Double.parseDouble(e.getText().toString().replace(",",""));}catch(Exception x){return 0;}}
 double expenseSum(JSONObject m,String cat){double s=0;JSONArray a=m.optJSONArray("expenses");if(a!=null)for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(cat==null||cat.equals(o.optString("category")))s+=o.optDouble("amount");}return s;}
 double missionPay(JSONObject m){double d=m.optDouble("days",1),h=m.optDouble("holiday",0);if(m.optBoolean("suburb"))return d*SUBURB+h*HOLIDAY;return (d==1?DAILY:d*MULTI)+h*HOLIDAY;} double reimbursable(JSONObject m,String payerKey,String amountKey){return "شخص".equals(payer(m,payerKey))?m.optDouble(amountKey):0;} double total(JSONObject m){return missionPay(m)+reimbursable(m,"hotelPayer","hotel")+reimbursable(m,"goPayer","ticketGo")+reimbursable(m,"backPayer","ticketBack")+reimbursable(m,"cancelGoPayer","cancelGo")+reimbursable(m,"cancelBackPayer","cancelBack")+expenseSum(m,null);} String payer(JSONObject m,String key){return m.optString(key,"شرکت");} void validate7(String end){if(end==null||end.trim().isEmpty())return;try{String[] p=end.trim().replace("-","/").split("/");if(p.length!=3)return;int y=Integer.parseInt(p[0]),mo=Integer.parseInt(p[1]),da=Integer.parseInt(p[2]);if(y<1900)return;Calendar e=Calendar.getInstance();e.setLenient(false);e.set(y,mo-1,da,0,0,0);e.getTime();Calendar n=Calendar.getInstance();n.set(Calendar.HOUR_OF_DAY,0);n.set(Calendar.MINUTE,0);n.set(Calendar.SECOND,0);n.set(Calendar.MILLISECOND,0);long days=(n.getTimeInMillis()-e.getTimeInMillis())/86400000L;if(days>7)throw new IllegalArgumentException("بیشتر از 7 روز از مأموریت گذشته و هزینه‌ها طبق Excel قابل پرداخت نیست");}catch(NumberFormatException x){}catch(IllegalArgumentException x){if(x.getMessage()!=null&&x.getMessage().contains("بیشتر از 7 روز"))throw x;}}
 void home(){base("مدیریت هزینه مأموریت");Button n=bt("＋ مأموریت جدید");n.setOnClickListener(v->{cur=new JSONObject();try{cur.put("expenses",new JSONArray());}catch(Exception e){}edit();});box.addView(n);ScrollView sc=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);for(JSONObject m:data){Button x=bt(m.optString("subject","بدون موضوع")+" | "+m.optString("destination","")+" | "+money(total(m))+" ریال");x.setOnClickListener(v->{cur=m;edit();});list.addView(x);}sc.addView(list);box.addView(sc,new LinearLayout.LayoutParams(-1,0,1));}
 int index(String[] a,String s){for(int i=0;i<a.length;i++)if(a[i].equals(s))return i;return 0;}
 void edit(){base(cur.length()==0?"مأموریت جدید":"ویرایش مأموریت");
  EditText form=ed("شماره فرم ماموریت"),service=ed("شماره سرویس"),subject=ed("موضوع"),dest=ed("مقصد"),start=ed("تاریخ شروع"),end=ed("تاریخ پایان"),startTime=ed("زمان شروع"),endTime=ed("زمان پایان"),days=ed("تعداد روز مأموریت"),holiday=ed("تعداد روز تعطیل"),hotel=ed("هزینه هتل"),go=ed("هزینه بلیط رفت"),back=ed("هزینه بلیط برگشت"),cancelGo=ed("هزینه کنسلی بلیط رفت"),cancelBack=ed("هزینه کنسلی بلیط برگشت"),goNo=ed("شماره بلیط رفت"),backNo=ed("شماره بلیط برگشت");
  form.setText(cur.optString("form"));service.setText(cur.optString("service"));subject.setText(cur.optString("subject"));dest.setText(cur.optString("destination"));start.setText(cur.optString("start"));end.setText(cur.optString("end"));startTime.setText(cur.optString("startTime"));endTime.setText(cur.optString("endTime"));days.setText(String.valueOf(cur.optDouble("days",1)));holiday.setText(String.valueOf(cur.optDouble("holiday",0)));hotel.setText(String.valueOf(cur.optDouble("hotel",0)));go.setText(String.valueOf(cur.optDouble("ticketGo",0)));back.setText(String.valueOf(cur.optDouble("ticketBack",0)));cancelGo.setText(String.valueOf(cur.optDouble("cancelGo",0)));cancelBack.setText(String.valueOf(cur.optDouble("cancelBack",0)));goNo.setText(cur.optString("goNo"));backNo.setText(cur.optString("backNo"));
  Spinner ps=spinner(people),ds=spinner(devices),hp=spinner(payers),gp=spinner(payers),bp=spinner(payers),cgp=spinner(payers),cbp=spinner(payers);ps.setSelection(index(people,cur.optString("person")));ds.setSelection(index(devices,cur.optString("device")));hp.setSelection(index(payers,payer(cur,"hotelPayer")));gp.setSelection(index(payers,payer(cur,"goPayer")));bp.setSelection(index(payers,payer(cur,"backPayer")));cgp.setSelection(index(payers,payer(cur,"cancelGoPayer")));cbp.setSelection(index(payers,payer(cur,"cancelBackPayer")));
  add("شماره فرم",form);add("شماره سرویس",service);add("نام کارشناس",ps);add("دستگاه",ds);add("موضوع",subject);add("مقصد",dest);add("تاریخ شروع",start);add("تاریخ پایان",end);add("زمان شروع",startTime);add("زمان پایان",endTime);add("روز مأموریت",days);add("روز تعطیل",holiday);
  CheckBox suburb=new CheckBox(this);suburb.setText("حومه تهران");suburb.setChecked(cur.optBoolean("suburb"));box.addView(suburb);
  add("هتل",hotel);add("پرداخت هتل توسط",hp);add("بلیط رفت",go);add("پرداخت بلیط رفت توسط",gp);add("شماره بلیط رفت",goNo);add("بلیط برگشت",back);add("پرداخت بلیط برگشت توسط",bp);add("شماره بلیط برگشت",backNo);add("کنسلی بلیط رفت",cancelGo);add("پرداخت کنسلی رفت توسط",cgp);add("کنسلی بلیط برگشت",cancelBack);add("پرداخت کنسلی برگشت توسط",cbp);
  TextView sum=tv("جمع کل: "+money(total(cur))+" ریال",19);box.addView(sum);
  LinearLayout exList=new LinearLayout(this);exList.setOrientation(LinearLayout.VERTICAL);box.addView(tv("ریز هزینه‌ها",18));box.addView(exList);render(exList,sum);
  Button ex=bt("＋ افزودن ردیف هزینه");ex.setOnClickListener(v->expenseDialog(exList,sum));box.addView(ex);
  Button save=bt("ذخیره مأموریت");save.setOnClickListener(v->{try{validate7(end.getText().toString());cur.put("form",form.getText().toString());cur.put("service",service.getText().toString());cur.put("person",ps.getSelectedItem().toString());cur.put("device",ds.getSelectedItem().toString());cur.put("subject",subject.getText().toString());cur.put("destination",dest.getText().toString());cur.put("start",start.getText().toString());cur.put("end",end.getText().toString());cur.put("startTime",startTime.getText().toString());cur.put("endTime",endTime.getText().toString());cur.put("days",num(days));cur.put("holiday",num(holiday));cur.put("suburb",suburb.isChecked());cur.put("hotel",num(hotel));cur.put("ticketGo",num(go));cur.put("ticketBack",num(back));cur.put("cancelGo",num(cancelGo));cur.put("cancelBack",num(cancelBack));cur.put("goNo",goNo.getText().toString());cur.put("backNo",backNo.getText().toString());cur.put("hotelPayer",hp.getSelectedItem().toString());cur.put("goPayer",gp.getSelectedItem().toString());cur.put("backPayer",bp.getSelectedItem().toString());cur.put("cancelGoPayer",cgp.getSelectedItem().toString());cur.put("cancelBackPayer",cbp.getSelectedItem().toString());if(!data.contains(cur))data.add(cur);save();home();}catch(Exception e){toast(e.getMessage());}});box.addView(save);
  Button pdf=bt("ساخت گزارش PDF");pdf.setOnClickListener(v->pdf(cur));box.addView(pdf);Button reset=bt("بازگشت");reset.setOnClickListener(v->home());box.addView(reset);
 }
 void expenseDialog(LinearLayout list,TextView sum){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);Spinner cat=spinner(cats);Spinner ti=spinner(tehranItems);EditText date=ed("تاریخ"),desc=ed("شرح"),invoice=ed("شماره فاکتور"),amount=ed("مبلغ");l.addView(cat);l.addView(ti);l.addView(date);l.addView(desc);l.addView(invoice);l.addView(amount);new AlertDialog.Builder(this).setTitle("افزودن هزینه").setView(l).setNegativeButton("انصراف",null).setPositiveButton("ثبت",(d,w)->{try{JSONArray a=cur.getJSONArray("expenses");JSONObject o=new JSONObject();o.put("category",cat.getSelectedItem().toString());o.put("tehranItem",ti.getSelectedItem().toString());o.put("date",date.getText().toString());o.put("desc",desc.getText().toString());o.put("invoice",invoice.getText().toString());o.put("amount",num(amount));a.put(o);render(list,sum);}catch(Exception e){toast(e.getMessage());}}).show();}
 void render(LinearLayout list,TextView sum){list.removeAllViews();JSONArray a=cur.optJSONArray("expenses");if(a!=null)for(int i=0;i<a.length();i++){final int k=i;JSONObject o=a.optJSONObject(i);Button x=bt(o.optString("category")+" | "+o.optString("desc")+" | "+money(o.optDouble("amount"))+" ریال  ✕");x.setOnClickListener(v->{a.remove(k);render(list,sum);});list.addView(x);}sum.setText("جمع کل: "+money(total(cur))+" ریال");}
 void save(){try{JSONArray a=new JSONArray();for(JSONObject m:data)a.put(m);getPreferences(0).edit().putString("data",a.toString()).apply();}catch(Exception e){}}
 void load(){try{JSONArray a=new JSONArray(getPreferences(0).getString("data","[]"));for(int i=0;i<a.length();i++)data.add(a.getJSONObject(i));}catch(Exception e){}}
 void toast(String s){Toast.makeText(this,"خطا: "+s,Toast.LENGTH_LONG).show();}
 void pdf(JSONObject m){try{PdfDocument d=new PdfDocument();PdfDocument.Page p=d.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());Canvas c=p.getCanvas();Paint q=new Paint();q.setTextSize(14);int y=35;String[] ls={"گزارش هزینه مأموریت","فرم: "+m.optString("form"),"سرویس: "+m.optString("service"),"کارشناس: "+m.optString("person"),"دستگاه: "+m.optString("device"),"موضوع: "+m.optString("subject"),"مقصد: "+m.optString("destination"),"شروع: "+m.optString("start")+" "+m.optString("startTime")+"  پایان: "+m.optString("end")+" "+m.optString("endTime"),"روز مأموریت: "+m.optDouble("days",1)+"  روز تعطیل: "+m.optDouble("holiday",0),"حق مأموریت: "+money(missionPay(m))+" ریال","هتل: "+money(m.optDouble("hotel"))+" ("+payer(m,"hotelPayer")+")","بلیط رفت: "+money(m.optDouble("ticketGo"))+" ("+payer(m,"goPayer")+")  برگشت: "+money(m.optDouble("ticketBack"))+" ("+payer(m,"backPayer")+")","کنسلی رفت: "+money(m.optDouble("cancelGo"))+" ("+payer(m,"cancelGoPayer")+")  برگشت: "+money(m.optDouble("cancelBack"))+" ("+payer(m,"cancelBackPayer")+ ")"};for(String s:ls){c.drawText(s,35,y,q);y+=25;}y+=8;c.drawText("ریز هزینه‌ها",35,y,q);y+=22;JSONArray a=m.optJSONArray("expenses");if(a!=null)for(int i=0;i<a.length()&&y<770;i++){JSONObject o=a.optJSONObject(i);c.drawText(o.optString("category")+" | "+o.optString("date")+" | "+o.optString("desc")+" | "+money(o.optDouble("amount")),35,y,q);y+=20;}y+=20;c.drawText("شهر تهران: "+money(expenseSum(m,"هزینه شهر تهران")),35,y,q);y+=20;c.drawText("بین شهری: "+money(expenseSum(m,"هزینه تردد بین شهری")),35,y,q);y+=20;c.drawText("درون شهری: "+money(expenseSum(m,"هزینه تردد درون شهری")),35,y,q);y+=20;c.drawText("سایر: "+money(expenseSum(m,"سایر هزینه ها")),35,y,q);y+=28;c.drawText("پرداختی کل: "+money(total(m))+" ریال",35,y,q);y+=22;c.drawText("روکش سند حسابداری",35,y,q);y+=20;c.drawText("واحد: "+m.optString("device"),35,y,q);y+=20;c.drawText("کارشناس: "+m.optString("person")+" | مقصد: "+m.optString("destination"),35,y,q);y+=20;c.drawText("موضوع: "+m.optString("subject"),35,y,q);y+=20;c.drawText("مبلغ به عدد: "+money(total(m))+" ریال",35,y,q);y+=20;c.drawText("مبلغ به حروف: "+amountWords(total(m)),35,y,q);d.finishPage(p);String fn="Mission_"+System.currentTimeMillis()+".pdf";if(Build.VERSION.SDK_INT>=29){ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,fn);v.put(MediaStore.Downloads.MIME_TYPE,"application/pdf");v.put(MediaStore.Downloads.IS_PENDING,1);Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);OutputStream o=getContentResolver().openOutputStream(u);d.writeTo(o);o.close();v.clear();v.put(MediaStore.Downloads.IS_PENDING,0);getContentResolver().update(u,v,null,null);d.close();share(u);}else{File f=new File(getExternalFilesDir(null),fn);OutputStream o=new FileOutputStream(f);d.writeTo(o);o.close();d.close();share(Uri.fromFile(f));}}catch(Exception e){toast(e.getMessage());}}
 void share(Uri u){Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/pdf");i.putExtra(Intent.EXTRA_STREAM,u);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"ارسال PDF"));}
}